### ISSUE TITLE
I started hapax cheon, an extension of chemlambda in javascript

### ISSUE THREAD

**Issue by mbuliga** [chorasimilarity/chemlambda-gui#7]
For those interested in the chemlambda project, see https://github.com/mbuliga/hapax and the README.

**Comment by chorasimilarity** [comment]
The official page of all chemlambda projects is now https://chemlambda.github.io/index.html

The repository chemlambda-gui is kept because of the content, otherwise, for new experiments, go to the official page.

The active branch of this repository is https://github.com/chorasimilarity/chemlambda-gui/tree/gh-pages/dynamic

_______
