### ISSUE TITLE
A-FO transition makes FOE nodes

### ISSUE THREAD

**Issue by ishanpm** [chorasimilarity/chemlambda-gui#8]
I think I understand the purpose of each node and transition, but the A-FO transition stood out to me, since it creates FOE nodes without creating FI nodes. The L-FO transition makes a FI node that corresponds to the FOE node, and the FI-FO transition only creates FO nodes. I'm not sure, but I think that creating FOE nodes without corresponding FI nodes could cause some terms to behave strangely, for example when using FO on a lambda term containing A-FO. Is there a reason for this transition's use of FOE?

**Comment by chorasimilarity** [comment]
Thank you for the interest. The A-FO does not create any problem,
because if the graph comes from a lambda term, then the FOE nodes will
migrate from the root to the leaves of any A-made tree. In the case of
 a L-FO or L-FOE pair, again of the graph corresponds to a lambda
term, the FI created will go from the root of the FO-made tree to the
leaves and the A created at the leaves will intercept them. That is
why btw the "shuffle trick" is so important. It occurs automatically
off course and it disentangles the multiplicated trees.


At http://imar.ro/~mbuliga/chemlambda-v2.html there are given some
examples where not any FI meets his FOE. Not mentioned there, but
encountered for example here
http://chorasimilarity.github.io/chemlambda-gui/dynamic/lisfact_2.html
(and solved here
http://chorasimilarity.github.io/chemlambda-gui/dynamic/lisfact_2_mod.html
), there is a problem when some FOE is destroyed by a *-T rewrite.

That is why I don't like the *-T rewrites and these can be avoided
either by restricting (in the case of lambda terms) to linear terms,
or alternatively, create a theory like linear lambda calculus, but
where we allow graphs (not terms) with an equal number of FRIN and
FROUT nodes (and use FROUT instead of T and introduce a FI-FROUT
rewrite instead of FI-T, for example). A good name for this
hypothetical generalization of linear lambda calculus would be
"conservative lambda calculus", because it forces a conservative
thinking. For example a TRUE
or FALSE term correspond to a graph with 2 FROUT and no FRIN and a
IFTHENELSE has one FROUT and 3 FRIN, so off course that we can make
boolean computing gates which are conservative, but we have to do it a
la Fredkin.

Same problem is for interaction combinators where the 1-valent nodes
and their rewrites which correspond to a *-T rewrite can be avoided.
I'll do this in few days (or maybe more, because summer) with "hapax".

**Comment by ishanpm** [comment]
Thank you for your quick reply! As for the T problem, it might be possible to alleviate that by using FOE-T instead of FOE2-T and FOE3-T, while leaving the FO(2,3)-T transitions as they are. I haven't tried this yet, since I'm on my phone, but it seems like it could make the reductions a little more consistent.

**Comment by chorasimilarity** [comment]
You are right maybe. I remember that the FOE2-T and FOE3-T were
introduced later, not earlier, but at that point I was more interested
into quines, or there is a single quine which comes from a lambda
term, namely Omega = (\x.xx)(\x.xx).
Again I mention hapax, which allows to define any system you like, but
faster. Is in javascript though, so slow compared with awk.

**Comment by ishanpm** [comment]
Hmm... Try this:
```
FO 1 free2 free3
FO 4 5 6
L 7 4 1
A 6 5 8
A 9 8 7
L 10 11 9
A 12 13 10
FO 11 13 12
```
This is the code for the lambda term \x.(\y.yy)(xx), attached to a FO. Because of the extra FOE created by the A on line 4, the expression does not multiply properly, and free2 and free3 are left with conjoined terms.

**Comment by chorasimilarity** [comment]
Not every term with a FO at the output can be duplicated, for example
the Y combinator. I'll thing about your example because is nice. Here
is late, tomorrow.

I tried your example in hapax. For this I did the following clumsy
thing (because I did not work yet on a good I/O). I added your mol as
{named:"mol_to_try",
edge:"1",
mol:[["FO", "1", "free2", "free3"],
["FO", "4", "5", "6"],
["L", "7", "4", "1"],
["A", "6", "5", "8"],
["A", "9", "8", "7"],
["L", "10", "11", "9"],
["A", "12", "13", "10"],
["FO", "11", "13", "12"]]
},
in the hapax-mol.js, then I changed the input in hapax-play.js, by

var molnamed = new Mol("mol_to_try");

then I opened hapax.html in the browser and got: initially

    [0] FO,0,11,12
    [1] FO,5,6,7
    [2] L,8,5,0
    [3] A,7,6,9
    [4] A,10,9,8
    [5] L,1,2,10
    [6] A,3,4,1
    [7] FO,2,4,3
    [8] FROUT,11
    [9] FROUT,12

and after I push start I get quick

    [0] FO,2,116,3
    [1] L,0,161,12
    [2] A,3,116,8
    [3] A,8,32,0
    [4] FROUT,11
    [5] FROUT,12
    [6] A,33,31,159
    [7] FOE,157,137,149
    [8] FO,62,115,117
    [9] A,117,115,33
    [10] A,120,118,31
    [11] FO,149,119,4
    [12] FO,137,118,120
    [13] A,4,119,32
    [14] L,159,157,11
    [15] FOE,161,62,2

**Comment by chorasimilarity** [comment]
I tried it with chemlambda, here is the result:
https://mbuliga.github.io/mol-to-try.html

Therefore it multiplies while it reduces in the same time.

**Comment by ishanpm** [comment]
The problem is dependent on evaluation order. If the FOE from the L reaches the FI before the FOE from the A. The problem occurs using quiner.sh with randomness disabled, for example.

**Comment by chorasimilarity** [comment]
True, here is an example in the random case
https://mbuliga.github.io/mol-to-try-2.html

I've seen this several times, for example if you have a sub-term which
is repeated in a term to reduce, it is sometimes not a good idea to
replace them with only one and a tree of FO.

**Comment by chorasimilarity** [comment]
OK, it is more complicated than the fact that A-FO produces FOE nodes.
In order to play with,
I made a folder in the hapax repository:

https://github.com/mbuliga/hapax/tree/master/chemlambda

which has a quiner program which allows you to choose if you want A-FO
and A-FOE to have the same outcome or if you want to have A-FO to
produce FO nodes and A-FOE to produce FOE nodes.

Your example is mol-to-try.mol. There is also a-fo-vero.mol which is
the pattern for A-FO. This can be used to check what A-FO does. In the
quiner-mod.awk you'll notice among parameters the one named
"afosameafoe", which is set to 0 (means that A-FO and A-FOE are not
the same).

Now I come to your example. The first problem can be seen when we take
just the lambda term you use, without duplication. This is the content
of molf-to-try-2.mol.

Then AF0 == AFOE this term (molecule) reduces to one which does have a
FOE node instead of a FO. This creates later the problem which leads
to  the siamese twins instead  of two copies of the term to be
duplicated.

In this sense you are right. If you make AFO != AFOE then the term
reduces to one which has only FO nodes, no FOE remained.

However, this is not enough. As you can see if you try to use
quiner-mod with all the wei_* parameters set to 1, but with
afosameafoe=0, this does not solve the problem.

A variant to try would be to inhibit completely the FO-FOE rewrite, so
the new FOE nodes created stay in place and wait for their FI to come
to them. The problem gets bigger, because if you do this there is no
shuffle trick and you are left with twice as many FOE nodes in the
siamese twins as before.

But if you inhibit FO-FOE and you also make A-L less probable as the
other rewrites, like wei_AL=5  (this is what I called the "viral"
reduction, the one which favors duplication over usual reduction),
then it works.

I recall that chemlambda does have conflicts, by design.

**Comment by chorasimilarity** [comment]
I repeat here what is the purpose of chemlambda:

Chemlambda does not magically provide a purely local reduction
algorithm for lambda terms, which solves what generations of smart
researchers tried unsuccessfully. You can still use it with linear
lambda terms, combinators or you can opportunistically program with it
on a case by case basis.

Chemlambda does offer a new possibility, not tried before, to make
molecular computers. There is a window of opportunity in between a
handful of random rewrites and universal computation which can be
interesting for practical applications. Not in lambda calculus, in
chemistry.

Because nature surely does not function by non-local algorithms, no
matter what programmers want.

**Comment by ishanpm** [comment]
A purely local reduction algorithm for lambda calculus is certainly not impossible; since it is computable, a Turing machine exists which implements it. Perhaps Chemlambda does not provide a complete model of lambda calculus, but I firmly believe that it is not very far.

One way to do this is to ensure that in molecules coming from lambda terms, all FI eventually either connect with their matched FOE, or are deleted by T. There are currently a handful of moves where this is not guaranteed. Among them are A-FO, which creates an unmatched FOE that could disrupt a FI; FO-FOE, which creates a potentially unmatched FI; and FOE2-T and FOE3-T, which delete a matched FOE and expose its FI to the world beyond. There might be others, but this property can be formally verified, so they won't be unknown for long.

All of these moves can be replaced with variants that preserve matches, without significantly affecting existing molecules. A-FO can simply not create FOE nodes, FO-FOE can require that both outputs of the FO be attached to FOE, and FOE2-T and FOE3-T can be replaced with FOE-T.

**Comment by ishanpm** [comment]
I added a button to my Javascript implementation to switch to my proposed alternate moveset.

**Comment by chorasimilarity** [comment]
Excellent! I made a page a page in hapax for it
http://imar.ro/~mbuliga/ishanpm-example.html

Just now I tried your editor with the 9_quine
https://github.com/chorasimilarity/chemlambda-gui/blob/gh-pages/dynamic/mol/9_quine.mol

FOE 1 11 10
FOE 9 17 16
FOE 7 15 14
A 8 6 5
A 16 14 6
A 17 15 7
FI 12 13 1
L 10 12 8
L 11 13 9

Is great, thank you!

I'll be back with some more ideas, there is much to say.

**Comment by chorasimilarity** [comment]
So your editor looks like this when I play with the 9_quine :)

https://chorasimilarity.wordpress.com/2019/06/24/play-with-quines-in-the-chemlambda-editor/

**Comment by ishanpm** [comment]
After thinking about this some more, I realized that there's still one last obstacle to modeling all terms: [Closures](https://en.wikipedia.org/wiki/Closure_(computer_programming)).

When a term is replicated, a wave of FOE nodes travels from output to input, covering all possible paths. However, if one of those inputs is the 2nd port of an enclosing L, it will cause trouble if that L is also replicated.

I'm not sure yet how to solve this, but it seems like the links between FI and FOE will have to be somehow made explicit, which will require additional node types. This may be out of scope for chemlambda, but it could be something to explore for hapax.

**Comment by chorasimilarity** [comment]
Yes, that's what happens with your term. One cheap solution, tried
before in other formalisms, is instead of having FO and FOE, to have
only FO, but to add some unique name to the pair of FI and FO created
by the duplication of the same L. Then, if a Fi and a FO with diferent
names meet, they duplicate, if they have the same name, they cancel.

I don't like this unique name story because it implies that we have an
infinity of different node types. However...

If we pass from 3-valent nodes to 4-valent nodes, then I think it is
possible to use the extra-bond to link the FI and FO created in the
same place. This is work in progress, namely to couple the hapax idea
of tokens and edge permutation with the oriented Reidemeister
rewrites. As soon as I have something I'll tell.

anyway hapax is strictly bigger than all this and flexible enough.

**Comment by chorasimilarity** [comment]
I just noticed that your alternate moveset is not the same as mine, in
the sense that you still keep a form of FO-FOE, while I don't. Without
FO-FOE your example works (as shown in hapax, see
http://imar.ro/~mbuliga/ishanpm-example.html )

Otherwise I inhibited your "dist3" and still (with or without "dist3"
actually) there are interersting effects when I "fractalize" quines,
for example. See this: http://imar.ro/~mbuliga/fractalize.html
As an example the "fractalized" 10_quine duplicates (sometimes).

The page, as well as the others, will be updated frequently.

**Comment by mbuliga** [comment]
I have this version with 6 3valent nodes [1], here are some examples from lambda calculus. Solves correctly your term.  All but one examples work as expected. Try to demolish it please. A lambda2mol parser in js would make things more fun. 
[1] http://imar.ro/~mbuliga/chbug.html

**Comment by ishanpm** [comment]
Interesting... What are the transitions for the GAMMA and DELTA nodes? (My transform code is a giant hack and I don't feel up to remembering how it works or reverse-engineering it at the moment.)

**Comment by chorasimilarity** [comment]
For the IC rewrites see Figure 2 page 9 [1]. Your giant hack works
well, I made lots of small modifications and some  bugs corrected. But
to see the alternative version of chemlambda with 6 nodes go to [2]
and look at "var transformListOrig = ..."

[1] https://pdfs.semanticscholar.org/6cfe/09aa6e5da6ce98077b7a048cb1badd78cc76.pdf

[2] http://imar.ro/~mbuliga/chbug.js

**Comment by ishanpm** [comment]
This does seem to resolve the issue with replicating A and FI, but it still doesn't address closures. Here is the lambda term \x.(\f.ff)(\y.xy), once again attached to a FO. Since the last abstraction contains a reference to x, a stray FOE is produced that messes with the outer replication. If you're lucky, the molecule might split correctly due to a race condition, but it usually doesn't.
```
L 1 2 3
L 4 5 6
A 2 5 4
FO 3 free7 free8
L 9 10 11
A 12 13 9
FO 10 13 12
A 11 6 1
```
I think there might be a way around this by making entering a lambda abstraction explicit, but I still need to test it to make sure. (Speaking of which, the transition system in my program is going to get a major rewrite soon.)

**Comment by chorasimilarity** [comment]
Thanks, I added it to the page with lambda terms. Anyway, no silver
bullet, just try by any means to duplicate the Y combinator applied to
something. (There always exists variants, detours, etc, but there is
no simple, universal, purely local, asynchronous algorithm for
reducing at the graphical level untyped lambda calculus.)

That is why I say again that the most interesting application is not
for decentralized computing but for local chemical manipulations
(molecular computers).

But is fun, I look forward to see your transition system.

**Comment by ishanpm** [comment]
Alright, the new transition system is working. This makes multi-node transitions a lot easier to write and read.

The alternate moveset in my program now has some additional nodes that I believe are capable of properly evaluating any lambda calculus expression. The SKI combinators can express any term in lambda calculus, but they do not bind variables, so they are easy to duplicate with FO nodes. (The U and Z nodes are inert and serve only to make Church numerals easier to read.)

I also tried extending the method of replication for L nodes with four additional types, called Lock, Open, Key, and Bypass. The Lock node is placed wherever a lambda abstraction uses variables from an outer abstraction, and the other three node types make sure that FOE is demoted to FO when it leaves the expression to be copied. Here is the same example \x.(\f.ff)(\y.xy) with a Lock node (make sure to use the alternate moveset to test it):

```
L 1 2 3
L 4 5 6
Lock 2 7
A 7 5 4
L 8 9 10
A 11 12 8
FO 9 12 11
A 10 6 1
FO 3 free13 free14
```

Both methods seem to work fine in my limited testing, although there is a considerable overhead from the number of nodes involved.

**Comment by chorasimilarity** [comment]
Cool, why don't you make a page with explanations? You know about
croissants and brackets [1]? (and my comment [2])

Could you also explain the other modifications, like for example the
ones regarding ports with signs, because I actually like that
initially the "bug" of not using edge orientations allows for easy
adaptation for interaction combinators.

Btw, re IC, do you know about this issue [3]? Go there and give the
guys a decent visualization :)

As I'm writing something about quines and other stuff and I'm using
adapted programs from your js version of my  chemlambda, are you
interested in co-authoring articles? In case, I would also need a
parser to mol format.




[1] https://pdfs.semanticscholar.org/6104/2374787bf6514706b49a5a4f0b74996979a0.pdf

[2] https://github.com/chorasimilarity/chemlambda-gui/issues/2#issuecomment-145168987

[3] https://github.com/moonad/Formality/issues/17

**Comment by ishanpm** [comment]
I didn't know about the Lambdascope presentation, although it looks like I came to a similar conclusion about scope delimiters. The use of Bypass nodes takes the place of numbered node types, which means that the number of node types is finite. I'll make a page with diagrams explaining it. I did discover some hangups that prevent certain graphs from reaching normal form, so I'll fix that first. 

The direction of edges in the new transition system is ignored, only the port numbers are checked. I just decided to make the edge labels in the transitions correspond to input and output to make them easier to read.

**Comment by chorasimilarity** [comment]
I have a piece of the graph and you have another, such that there are
some edges from my piece to your piece (i.e. I have some half-edges
and you have others). We have a predefined algorithm to communicate
and transfer nodes linked by these edges. But you don't know in
advance what my piece of graph is, and I don't know what your piece
is, in advance. How do we put delimiters so that the computation
works? (supposing that we already know the algorithm of communication
and transfer, which itself is purely local, which is another
non-obvious problem.)

**Comment by ishanpm** [comment]
It probably depends on the exact details of the communication algorithm used. Lambda terms usually only accept either one input or a fixed number of curried inputs, so it might be a little tricky to set up a system that can even handle multiple inputs along the same channel. This sounds like a task best suited to my other favorite greek-letter-named system, Pi Calculus. The asynchronous computation and the reusable communication channels sound like a perfect fit for a graph-based model, although the many-to-many connections involved might be difficult to implement.

**Comment by ishanpm** [comment]
If you're talking about a single graph running across multiple environments, it should be possible to send only the type and port number of the node connected to an external half-edge. My transform syntax does have a way to say where new nodes appear, so a similar system could be used to decide which environment will get each new node and where to put the new edges.

**Comment by chorasimilarity** [comment]
I don't believe that's true. Say we take your example of a FO applied
to  \x.(\f.ff)(\y.xy)

L 1 2 3
A 10 6 1
L 8 9 10
FO 9 12 11
A 11 12 8
FO 3 13 14
L 4 5 6
A 2 5 4


But now you have only FO applied to  \x.((\f.ff)v)

L 1 2 3
A 10 6 1
L 8 9 10
FO 9 12 11
A 11 12 8
FO 3 13 14

and I have \y.uy

L 4 5 6'
A 2' 5 4

You have the half edges 13, 14 (which are of no concern here, for
example you may actually have a bigger graph, say FIRST (PAIR 13 14)
and also the half edges 2, 6.

I have the half edges 2' and 6'.

We both know that we are going to link 2 with 2' and 6 with 6', but
otherwise you don't know my graph and I don't know yours.

Arrow 2 2'
Arrow 6' 6

That's all we know, each.

Questions:

1. what do you need to know from me in order to add a lock  to your graph

Rewrite:
Arrow 2 2'
into
Lock 2 7
Arrow 7 2'

2. what do I need to know from you that I don't have to do anything to my graph?

**Comment by ishanpm** [comment]
Ohhh you're talking about the Lock nodes. I thought you were talking about distributed computation using Chemlambda.

The Lock nodes are intended to be added when creating a graph of a lambda term, with the number inserted corresponding to the De Bruijn index of the variable to be replaced. When evaluating an expression, they will automatically be added using only local graph-rewrite rules, same as the rest of Chemlambda.

There is a simple way to make sure a pre-existing graph has consistent delimiters: Assign a depth number to each node, where adjacent nodes have the same depth, except when connected to scoping ports. These are the first two ports of L, the output port of Lock and Open, and the input port of Key. Nodes connected to a scoping port should instead have a depth one higher than the connected node (unless both ports along the edge are scoping). If it is possible to assign depth numbers consistently, the delimiters on the graph are correct.

At least, that's the theory. I'm still testing to make sure it all works out.

**Comment by chorasimilarity** [comment]
Sure, I know, that's why I asked this questions. De Bruijn indices are
global! Some things can be done, for limited applications. Bring on
the type police. But all in all, you get lots of complexity, which is
not worth the effort. Why not keep it simple? Like nature does. If it
is technically possible then it is possible, regardless the added
complexity and police.

**Comment by mbuliga** [comment]
OK, try to kill this one :)  http://imar.ro/~mbuliga/kali24.html


----- Original Message -----

**Comment by chorasimilarity** [comment]
The official page of all chemlambda projects is https://chemlambda.github.io/index.html

The repository chemlambda-gui is kept because of the content, otherwise, for new experiments, go to the official page.
