### ISSUE TITLE
Javascript Chemlambda editor

### ISSUE THREAD

**Issue by ishanpm** [chorasimilarity/chemlambda-gui#9]
I'm making a Javascript implementation of Chemlambda. It's very hacked together right now, but it works, so I thought I'd share it. I'll move it to my GitHub page once it's a little nicer.

~~https://jsfiddle.net/ishanpm/0k98ceha/show~~  

Edit: It's on GitHub now! https://ishanpm.github.io/chemlambda-editor/

To use it, simply paste a .mol file into the text box at the bottom and click "Import .mol", then mouse over nodes that have an available move to transform them. If you're feeling extra fancy, you can also construct molecules using the toolbar at the top.

**Comment by chorasimilarity** [comment]
Great! I tried it with the 9quine from the library of molecules
https://github.com/chorasimilarity/chemlambda-gui/tree/gh-pages/dynamic/mol

Then I tried a much bigger molecule and it took a lot of time to put
it on the screen. Maybe you can make it to put the nodes and the links
progressively on screen. That's what I did.

Excellent, looking forward to play with it!

**Comment by chorasimilarity** [comment]
The mechanics is good, but there are some problems with the rewrites
and with the port types.

So try with this mol

https://github.com/chorasimilarity/chemlambda-gui/blob/gh-pages/dynamic/mol/allmoves.mol

and compare with the rewrites as in

http://chorasimilarity.github.io/chemlambda-gui/dynamic/moves.html

What I notice:
- by "link" I mean a link between two port nodes.
- Each port node has a type "in" or "out" and another type "left",
"right", "middle".
- The color of the port node encodes "in" or "out", so there should be
two colors of port nodes (I see 3 colors in your fiddle). The other
type "left", right", "middle" is encoded in the radius of the port
node.
- each link should connect a port node "in" with a port node "out"
- I don't see the Arrow nodes, which are 2-valent nodes, in mol
notation "Arrow a b"

**Comment by ishanpm** [comment]
Every node has the same three ports: Red in, green in/out, blue out. These correspond to the first, second, and third edges in the .mol file directly. This made the moves slightly easier to implement, at the expense of not having a clear difference between green in and green out nodes. As a small workaround, I arranged the color scheme so that all of the primary-colored nodes are 1in 2out, and the others are 2in 1out (except T). I will add the original color scheme soon (although I honestly find this way easier to read).

Arrow, FRIN, and FROUT don't directly affect the evolution of a molecule, so they aren't yet implemented. The only thing this makes impossible are Arrow bubbles and FRIN-Arrow-FROUT connections, so I decided to leave them out for now.

**Comment by chorasimilarity** [comment]
OK, I added an exposition of chemlambda and hapax mol notation and rewrites,
https://mbuliga.github.io/hapax/chemlambda-and-hapax.html

Arrow directly affects the evolution of a molecule, because you need
these nodes to make the right rewiring, then to eliminate them. I
believed several times that it is possible not to use Arrow elements
and then I found counterexamples. If you find a way then explain.

**Comment by ishanpm** [comment]
`Arrow X Y` effectively means, "Unify edge X with edge Y." It's useful, because it abstracts away what X and Y are actually connected to. In Hapax (if I understand correctly), Arrow works by having a separate move for each output port of every other node type. However, in my program, I work with half-edges directly. Instead of having graph rewrites that take a group of nodes and replace it with another group, the moves are implemented as scripts that add and remove nodes, then permute the connections between them. Every transition is basically hardcoded (like I said, this project is very hacked together) but they can be a little more flexible than graph rewrites.

**Comment by ishanpm** [comment]
Out of curiosity, what was the large file you tried to load? I just fixed a big performance bottleneck, so it should load quickly now.

**Comment by chorasimilarity** [comment]
I think this one:

https://github.com/chorasimilarity/chemlambda-gui/blob/gh-pages/dynamic/mol/5_16_quine_bubbles_hyb_double.mol

**Comment by chorasimilarity** [comment]
By mistake I commented on the other issue about your excellent editor.
Here are some further remarks:

- it goes great in the mouse hovering variant, but less in the
"automatic" variant, I think this is because it has a predefined order
to visit the nodes and to submit (the edges) to the rewrites.

- but is fast, wish I have a variant for the hapax version of
chemlambda which works differently (more later)

- I had a very hacked "universal visualiser" for the html simulations
from the collection
https://figshare.com/articles/The_Chemlambda_collection_of_simulations/4747390/1

I put it now here: https://github.com/mbuliga/hapax/tree/master/chemlambda

There is a script getmoves.sh which extracts the rewrites from a html
file, then there is a universal.html which uses the array of rewrites
to execute them. But is hacked and not fast. It would be nice to be
able to see them at a speed comparable with the one of the animations
obtained from screencasting. It can also be used with the output of a
new quiner computation, although your editor, once it is polished at
the edges, makes this superfluous.

- I think about at least 3 game-like experiences. The first two would
be nice to be in the form of a phone app, the 3rd is better on a pc.

1) Feed the quine game, where tokens (a la hapax) are fed to the quine
to keep it alive. Also it is possible to combine quines (see the hyb
functions in hapax). When I say a la hapax, the token, which is a
small molecule, when close to a pattern, triggers the reaction. To
illustrate this I made a (fake, because scripted) page for the beta
rewrite http://imar.ro/~mbuliga/beta-token.html

Now oyu may think about these tokens as coins, or gas if you are an
ethereum fan. The more serious side would be to measure the cost of a
computation.

2) Divination games. Seriously. Vajra chains of awareness (I was
notified about this) or i-ching. I'd take the name, location, etc as
input, then produce a graph and reduce it, then evaluate it. All
according to some divination rules. Why not? Asia is waiting.

3) this one is for pc. Think about a program as written on a piece of
paper. If you cut this paper in two, by a horizontal cut, what you get
are two pieces of programs which usually are technically correct. But
what if you cut the piece of paper by a vertical cut? You'll split
commands in half, they don't make sense. More than that, if you
combine the cuts, by making them go horizontally an dvertically, you
get nonsense.

However, it would be interesting to have a text editor (for programs)
which allows you to make these cuts, so that the program you write is
split in several parts, some commands are split, etc. If you look at
commands like

let x=a in b

if a then b else c

a=b

they all make sense if split, if you think about them in terms of
graphs and their reductions. In lambda terms say let x=a in b is made
of 2 nodes, ifthenelse the same, ...

Therefore suppose you can "compile" the program to a graph and you can
then split the graph in several pieces, which are reduced
independently, as much as possible, then the pieces engage in random
interactions ones with the others (they exchange some nodes), and they
reduce until the result is obtained.

Looks to me like the most simple way to make a game like distributed
computing. Do you want a program to play chess? Simple: write the
rules (and some internal logic of the players) as a program, then cut
the program in 3: player A, player B, table, then reduce.

**Comment by ishanpm** [comment]
The way the auto run mode currently works is very simple: It iterates through the list of nodes, and executes the move for any node that has a move. Since new nodes are added to the end, this creates a problem where it will sometimes get stuck in a loop, infinitely creating more nodes and ignoring other possible moves. I can change it to gather all the valid moves, then execute them at once. I was also thinking of including a delay-based mode, where each move has a specified delay, and only executes once that delay is finished. It would have a similar effect to weighted random choice, while still running in parallel.

**Comment by chorasimilarity** [comment]
Psihedelic, I added it to the blog post: https://youtu.be/iiDDXtAnSR8

**Comment by chorasimilarity** [comment]
I tried several other mol files from the library.

(a) some of them do not appear as they should, I think because there
is no Arrow element and also perhaps because in my mol files there are
empty lines. Quiner ignores the lines with less than 2 and more than 4
fields.

(b) some of them do not reduce as they should. The reduction stops in
the middle. I think a reason is that there is no Arrow element and
COMB rewrites, but I can't put the finger on the exact reason. I tried
with the mol A a b c, L c b a and it reduces correctly

(c) As concerns the order of reductions, I believe it would be simple
to have an array with the numbers of the nodes which is shuffled
randomly and then the nodes are accessed from this array. Same about
an array of rewrite patterns, they should be tried in random order.

(d) perhaps related to (b), it does matter if you make one
reduction/cycle or you do simultaneously several of them. For this you
definitely need Arrow.

**Comment by ishanpm** [comment]
(a) My .mol parser ignores all lines that don't have exactly 2 or 4 fields. Blank lines are ignored, but so are lines like in 10_9_quine.mol that have 5 fields. (What do those extra fields mean?)

(b) I think that is a side effect of a particular reduction order. Favoring rewrites that create more nodes seems to result in deadlocks involving FI nodes. There is also a bug in how T nodes are handled that could be causing problems.

(c) That would work, although keeping a cache of transformable nodes will be more optimal.

(d) I'll add the Arrow nodes and see how that affects things.

**Comment by ishanpm** [comment]
I updated the reduction strategy. Slow mode picks a random move each frame, and fast mode executes all possible moves in a random order. I think you'll find this makes quines much more fun to watch!

I also made the .mol reader a little more lax, so it simply ignores fields past the number a node is supposed to have.

**Comment by chorasimilarity** [comment]
Thank you! Looking forward to play with it. Please put it somewhere
sometime, for reference and due credits.

Comment on a previous point, relevant to this one. The problem, for
me, is the following: given the simplest algorithm, which does random
local rewrites, based on only local information, is there a rewrite
system which can do interesting things (lik euniversal computation or
like life)? I have doubts that there is a rewrite system which ca,
with only the simplest algorithm, reduce any untyped lambda term. But
I try, who knows? /

You mentioned that because Turing machines are local, it follows that
there should be one. It does not anwer to the problem I have.

Btw, re Turing machines, have you noticed that in the quiner monster
there are also some extra nodes, for fun, and rewrites for a busy
beaver? The explanation is here:
https://chorasimilarity.github.io/chemlambda-gui/dynamic/turingchem.html

Finally, if oyur reduction algorithm uses a list of nodes, say (it has
to, js does not have associative arrays) then the reduction algorithm
is not the "right" one, unless you destroy the extrta information by
randomizing the list. Also, even the greedy algorithm which says "at
every time step make as many rewrites as possible" is not exactly
deterministic because, due to the conflict of left patterns for
rewrites, for a given graph there may be more than one maximal
partition o fit into active parts. So even if there is a order of
preference for rewrites, this does not eliminate this phenomenon.

Re: the https://github.com/chorasimilarity/chemlambda-gui/blob/gh-pages/dynamic/mol/10_9_quine.mol
it should be in the mola folder, not the mol folder. I have many of
those, the last field tells whose "actor" the node belongs to. But
(there is a simple script to see this) there are if I remember
correctly, 427 valid mol files in that lib.

**Comment by chorasimilarity** [comment]
Works wonderfully!

**Comment by mbuliga** [comment]
I made some very slight modifications to your "editor" (actually a js version of chemlambda) and turned into a feed-the-quine page here: 
https://mbuliga.github.io/feed-the-quine.html 

Please tell me if this is OK or if I change anything. 

I just added some mol files from the library and changed a bit the animation (more fluid, eliminated the annoying dot strobe)

**Comment by ishanpm** [comment]
Go ahead and make changes if you want. Just keep in mind that I'll be making lots of changes to this version as well.

**Comment by chorasimilarity** [comment]
Great, thank you. Looking forward fo the changes. Again, please put
the code somewhere for reference. Or discuss ways of collaboration. I
don't want to uglify your code, only I was asking for a chemlambda.js
for years, for these visualisations reasons. Now much more is
possible, in principle.

Anyway I want to add some options:

a) random shuffle of the edges of a quine, to produce another graph
b) "mutation", same as random shuffle, only limited to a pair of nodes
linked by an edge
c) hybridization of two quines
d) a limitation on the number of nodes, i.e. if the no of nodes > 500
say then speed = 0. Or better, then only the moves which lower the no
of nodes apply.

And go on with hapax.

**Comment by mbuliga** [comment]
I put an ES5 compatible version at my homepage http://imar.ro/~mbuliga/feed-the-quine-es5.html and added more choices. 

Everything well, does not block even the dumbest browser. Only care is with with the use of ">>" with  claudia_starmaker because it produces lots of stars quick, therefore use ">>" with that choice only few seconds. 
 

----- Original Message -----

**Comment by ishanpm** [comment]
I've moved the project to GitHub, which is where I'll make all further changes.

The live page is here: https://ishanpm.github.io/chemlambda-editor  
The source code is here: https://github.com/ishanpm/chemlambda-editor

There are also many issues filled out on the repository, indicating features that I'd like to add. If there's something you'd like to see, feel free to add an issue.

**Comment by mbuliga** [comment]
Thank you, 

I've updated the link to your chemlambda.js. I saw the issues, I want to concentrate on the 4-valent story, and on hapax. Do hope that until Autumn there will be something really beautiful to show. 

----- Original Message -----

**Comment by chorasimilarity** [comment]
2 quick facts:

1) does your prototype editor work on safari? my pages here [1] or
here [2] don't, why?

2) could you change the link to the chemlambda repository from your
readme [2] into
https://github.com/chorasimilarity/chemlambda-gui/blob/gh-pages/dynamic/README.md

[1] https://mbuliga.github.io/feed-the-quine.html

[2] http://imar.ro/~mbuliga/feed-the-quine-es5.html

[3] https://github.com/ishanpm/chemlambda-editor/blob/master/README.md

**Comment by mbuliga** [comment]
It looks like you don't use the arrows orientations, so I further modified your nice js version and I added Interaction Combinators and a quine by Lafont! 
https://mbuliga.github.io/find-the-quine-step-by-step.html 

Am I missing something? There is one LOC which I didn't get it, which might keep some info about the arrow orientation: 

    findNode(i+k+1).dir = valence[k];

in the function addNodeAndEdges.

**Comment by ishanpm** [comment]
Yup, that is indeed the purpose of that line. The ports have an extra property `dir`, which is 0 for input ports and 1 for output ports. That data is stored for each node type in `nodeValence` This is used in the link function, to prevent connecting inputs to inputs or outputs to outputs. It isn't used in the transform functions, because the shape of the transformations already ensures that the direction of the links stay consistent.

Sorry I haven't really been doing anything with this lately. I'm working at an internship, so I haven't had much time to focus on personal projects.

**Comment by chorasimilarity** [comment]
Yes but it does allow to link input to input or output to output,
that's why I could add Interaction Combinators nodes GAMMA and DELTA
with nodeValence [0,0,0] and connect them as I like in mol strings
(from molLib.js) and add IC rewrites from them which work well.

Good luck with the internship, looking forward for more trans.actions :)

**Comment by chorasimilarity** [comment]
I made a landing page for all chemlambda projects here

https://chemlambda.github.io/index.html

**Comment by chorasimilarity** [comment]
No more input.
